routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\ProjectController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// RouFile::exists($product->product_images)te::get('/', function () {
//     return view('welcome');
// });
Route::get('/', [IndexController::class, 'index'])->name('index');

Route::get('index', [IndexController::class, 'index'])->name('index');

Route::get('my-captcha', [IndexController::class, 'myCaptcha'])->name('myCaptcha');

Route::get('refresh_captcha', [IndexController::class, 'refreshCaptcha'])->name('refresh_captcha');

Route::get('terms-and-conditions', [IndexController::class , 'termsConditionPage'])->name('terms-conditions');

Route::get('return-policy', [IndexController::class , 'returnpolicy'])->name('return-policy');

Route::get('privacy-policy', [IndexController::class , 'privacypolicy'])->name('privacy-policy');

Route::get('contact-us', function () {
    return view('contactUs');
})->name('contact-us');

Route::get('products/{id}', [ProductsController::class, 'singleCategory'])->name('products.list');

Route::get('products/{parentslug}/{slug}', [ProductsController::class, 'singleProduct'])->name('product.single');

Route::get('product/{pid}/options', [ProductsController::class, 'designProduct'])->name('design.option');

Route::get('products/{parentslug}/{slug}/designs', [ProjectController::class, 'browseDesigns'])->name('designs.list');

Route::get('products/{parentslug}/{slug}/customDesign/{uid}', [ProjectController::class, 'customDesigns'])->name('designs.custom');

Route::post('products/{parentslug}/{slug}/customDesign/{uid}/save', [ProjectController::class, 'customDesignsSave'])->name('designs.custom.save');

Route::get('cart', [ProductsController::class, 'cart'])->name('cart');

Route::delete('cart/{id}/remove', [ProductsController::class, 'removeCart'])->name('cart.remove');

Route::post('contactus/save', [IndexController::class, 'contactUs'])->name('contactus.save');

Route::any('/products/{parentslug}/{slug}/designs/customize/{id}', [ProjectController::class, 'index'])->name('design.customization');

Route::get('logout', function () {
    return view('index');
})->name('logout');

// Route::post('product/design/project/step', [ProjectController::class, 'changeStep']);

// Route::middleware(['auth:sanctum', 'verified', 'role:User'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

// Route::middleware(['auth:sanctum', 'verified', 'role:User'])->get('/order', function () {
//     return view('order');
// })->name('order');

Route::group(['middleware' => 'role:User,Admin'], function () {
    Route::get('dashboard', [HomeController::class, 'index'])->name('user.dashboard');
    Route::get('order', [HomeController::class, 'orders'])->name('user.order');
    // Route::get('cart', [HomeController::class, 'carts'])->name('user.cart');
    // Route::get('checkout', [HomeController::class, 'checkout'])->name('user.checkout');
});

Route::get('product/application/designs/addon/{categoryId}', [ProjectController::class, 'getProductAddOns']);

Route::post('review/post/{pid}', [ProductsController::class, 'saveReview'])->name('post.review');

Route::get('checkout', [HomeController::class, 'checkout'])->name('checkout');

Route::post('search', [ProductsController::class, 'search'])->name('search.post');

Route::post('order/save', [HomeController::class, 'saveCheckout'])->name('checkout.save');

Route::get('payment-success', [HomeController::class, 'payment_success']);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    protected $primaryKey = 'id';
    
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/user/cart.blade.php
<x-app-layout>
    <x-slot name="logo">
        {{-- <x-jet-authentication-card-logo /> --}}
    </x-slot>
      <!-- Subheader Start -->
  <div class="sigma_subheader primary-bg">

    <img src="{{  asset('img/textures/3.png') }}" class="texture-3" alt="texture" />

    <!-- Top Left Wave -->
    <div class="sigma_subheader-shape circles">
      <div class="circle circle-lg circle-1 primary-dark-bg"></div>
      <div class="circle circle-sm circle-2 bg-white"></div>
      <div class="circle circle-md circle-3 secondary-bg"></div>
    </div>

    <!-- Bottom Wave -->
    <div class="sigma_subheader-shape waves">
      <div class="wave"></div>
      <div class="wave"></div>
    </div>

    <div class="container">
      <div class="sigma_subheader-inner">
        <h1>Cart</h1>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Pages</a></li>
            <li class="breadcrumb-item active" aria-current="page">Cart</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
  <!-- Subheader End -->

 <!--Cart Start -->
 <div class="section">
    <div class="container">

      <!-- Cart Table Start -->
      <table class="sigma_responsive-table">
        <thead>
          <tr>
            <th class="remove-item"></th>
            <th>Product</th>
            <th class="text-center">Job Size</th>
            <th>Quantity</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($cartData as $cart)
          {{-- {{ dd($cart) }} --}}
          <tr>
            <td class="remove">
              <button type="button" class="close-btn close-danger remove-from-cart">
                <span></span>
                <span></span>
              </button>
            </td>
            <td data-title="Product">
              <div class="sigma_cart-product-wrapper">
                <img src="{{ $cart['designImage'] }}" alt="prod1">
                <div class="sigma_cart-product-body">
                <h6>{{ $cart['project_name'] }}</h6>
                <p>Product : {{ $cart['product_name'] }} </p>
                <p>Category: {{ $cart['category_name'] }}</p>
                @if (count($cart['addons']) > 0)
                @foreach ($cart['addons'] as $key => $addon)
                <p>{{ $key }}: {{ $addon }}</p>
                @endforeach
                @endif
                </div>
              </div>
            </td>
            <td class="quantity text-center" data-title="Quantity">
                <strong class="text-center">{{ $cart['job_size'] }}</strong>
            </td>
            <td class="quantity" data-title="Quantity">
              <strong class="text-center">{{ $cart['quantity'] }}</strong>
            </td>
            <td data-title="Total"> <strong>Rs. {{ $cart['price'] }}/-</strong> </td>
          </tr>
          @endforeach
        </tbody>
      </table>
      <!-- Cart Table End -->

      <!-- Coupon Code Start -->
      {{-- <div class="row">
        <div class="col-lg-5">
          <div class="form-group mb-0">
            <div class="input-group mb-0">
              <input type="text" class="form-control" placeholder="Enter Coupon Code" aria-label="Coupon Code">
              <div class="input-group-append">
                <button class="sigma_btn-custom shadow-none" type="button">Apply</button>
              </div>
            </div>
          </div>
        </div>
      </div> --}}
      <!-- Coupon Code End -->

    </div>
  </div>
  <!-- Cart End -->
  <a class="btn btn-success" href="{{ route('user.checkout') }}">CHECKOUT</a>
</x-app-layout>

resources/views/user/checkout.blade.php
<x-app-layout>
    <!-- Subheader Start -->
    <div class="sigma_subheader primary-bg">

        <img src="{{  asset('img/textures/3.png') }}" class="texture-3" alt="texture" />

        <!-- Top Left Wave -->
        <div class="sigma_subheader-shape circles">
            <div class="circle circle-lg circle-1 primary-dark-bg"></div>
            <div class="circle circle-sm circle-2 bg-white"></div>
            <div class="circle circle-md circle-3 secondary-bg"></div>
        </div>

        <!-- Bottom Wave -->
        <div class="sigma_subheader-shape waves">
            <div class="wave"></div>
            <div class="wave"></div>
        </div>

        <div class="container">
            <div class="sigma_subheader-inner">
                <h1>Checkout</h1>
            </div>
        </div>
    </div>
    <!-- Subheader End -->

    <!-- Checkout Start -->
    <div class="section">
        <div class="container">

            <form method="post" action="{{ route('checkout.save') }}">
                @csrf
                <div class="row">
                    <div class="col-xl-6">

                        {{-- <!-- Login -->
                        @if(!Auth::check())
                            <div class="sigma_notice">
                                <p>Are you a returning customer? <a href="#">Click here to login</a> </p>
                            </div>
                        @endif
                        <div class="sigma_notice-content">
                            <form action="{{ route('login') }}" method="post" >
                                <div class="row">
                                    <div class="col-xl-6 form-group">
                                        <label>Email Address</label>
                                        <input type="text" class="form-control" name="login-email"
                                            placeholder="Email Address" value="">
                                    </div>
                                    <div class="col-xl-6 form-group">
                                        <label>Password</label>
                                        <input type="password" class="form-control" name="login-pass" placeholder="Password"
                                            value="">
                                    </div>
                                    <div class="col-12 form-group">
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="rememberMe">
                                            <label class="custom-control-label" for="rememberMe">Remember Me</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <button type="submit" class="sigma_btn-custom" name="button">Login</button>
                                    </div>
                                </div>
                            </form>
                        </div> --}}
                        <!-- Coupon Code -->
                        {{-- <div class="sigma_notice">
                            <p>Do you have a coupon code? <a href="#">Click here to apply</a> </p>
                        </div> --}}
                        {{-- <div class="sigma_notice-content">
                            <p>If you have a coupon code, apply it below</p>
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Coupon Code">
                                <div class="input-group-append">
                                    <button class="sigma_btn-custom shadow-none btn-sm" type="button">Apply
                                        Code</button>
                                </div>
                            </div>
                        </div> --}}

                        <!-- Buyer Info Start -->
                        <h4>Billing Details</h4>
                        <div class="row">
                            <div class="form-group col-xl-12">
                                <label>Name <span class="text-danger">*</span></label>
                                <input type="text" placeholder="Name" name="name" class="form-control" value="{{ Auth::user()->name }}"
                                    required="" readonly>
                            </div>
                            <div class="form-group col-xl-12">
                                <label>Company Name</label>
                                <input type="text" placeholder="Company Name (Optional)" name="company_name"
                                    class="form-control" value="{{ $userDetails ? $userDetails->company_name : '' }}">
                            </div>
                            <div class="form-group col-xl-12">
                                <label>Country <span class="text-danger">*</span></label>
                                <select class="form-control" name="country" required value="{{ $userDetails ? $userDetails->country : '' }}">
                                    <option value="">Select a Country</option>
                                    <option value="India" selected="$userDetails ? $userDetails->country : ''">India</option>
                                </select>
                            </div>
                            <div class="form-group col-xl-6">
                                <label>Street Address 1 <span class="text-danger">*</span></label>
                                <input type="text" placeholder="Street Address One" name="street_address_1" class="form-control"
                                    value="{{ $userDetails ? $userDetails->street_address_1 : '' }}" required="">
                            </div>
                            <div class="form-group col-xl-6">
                                <label>Street Address 2</label>
                                <input type="text" placeholder="Street Address Two (Optional)" name="street_address_2"
                                    class="form-control" value="{{ $userDetails ? $userDetails->street_address_2 : '' }}">
                            </div>
                            <div class="form-group col-xl-12">
                                <label>Town / City <span class="text-danger">*</span></label>
                                <input type="text" placeholder="Town/City" name="town_city" class="form-control" value="{{ $userDetails ? $userDetails->town_city : '' }}"
                                    required="">
                            </div>
                            <div class="form-group col-xl-6">
                                <label>Phone Number <span class="text-danger">*</span></label>
                                <input type="text" placeholder="Phone Number" name="phone_number" class="form-control" value="{{ $userDetails ? $userDetails->phone_number : '' }}"
                                    required="">
                            </div>
                            <div class="form-group col-xl-6">
                                <label>Email Address <span class="text-danger">*</span></label>
                                <input type="email" placeholder="Email Address" name="email" class="form-control" readonly
                                    value="{{ Auth::user()->email }}" required="">
                            </div>
                        </div>
                        <!-- Buyer Info End -->

                    </div>
                    <div class="col-xl-6 checkout-billing">
                        <!-- Order Details Start -->
                        <table class="sigma_responsive-table">
                            <thead>
                                <tr>
                                    <th>Product</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach( $checkoutData as $checkout )
                                <tr>
                                    <td data-title="Product">
                                        <div class="sigma_cart-product-wrapper">
                                            <div class="sigma_cart-product-body">
                                                <h6> {{  $checkout['product_name'] }} </h6>
                                                <p>{{ $checkout['category_name'] }}</p>
                                                @if (count($checkout['addons']) > 0)
                                                @foreach ($checkout['addons'] as $key => $addon)
                                                <p>{{ $key }}: {{ $addon }}</p>
                                                @endforeach
                                                @endif
                                            </div>
                                        </div>
                                    </td>
                                    <td data-title="Quantity">{{ $checkout['quantity'] }}</td>
                                    <td data-title="Total"> <strong>Rs. {{ $checkout['price'] }}</strong> </td>
                                </tr>
                                @endforeach
                                <tr class="total">
                                    <td>
                                        <h6 class="mb-0">Grand Total</h6>
                                    </td>
                                    <td></td>
                                    <td> <strong>Rs. {{ $totalAmount }}</strong> </td>
                                </tr>
                            </tbody>
                        </table>

                        <button type="submit" class="sigma_btn-custom primary btn-block">Place Order</button> 

                        <!-- Order Details End -->
                        <img src="{{ asset('img/paymentOption.png') }}" style="width:100%; height: auto; margin-top: 20px" />

                    </div>
                </div>
            </form>

        </div>
    </div>
    <!-- Checkout End -->

</x-app-layout>

resources/views/user/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                {{-- <x-jet-welcome /> --}}
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/user/footer.blade.php
    <!-- Footer Start -->
    @if(!Request::is('login'))
    <footer class="sigma_footer sigma_footer-dark">

        <!-- Middle Footer -->
        <div class="sigma_footer-middle">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-12 footer-widget">
                        <img src="https://via.placeholder.com/155x50" class="mb-4" alt="logo">
                        <p>9000 Regency Parkway, Suite 400 Cary, NC 27518</p>
                        <ul class="sigma_sm">
                            {{-- <li> <a href="#"> <i class="fab fa-facebook-f"></i> </a> </li>
                            <li> <a href="#"> <i class="fab fa-instagram"></i> </a> </li>
                            <li> <a href="#"> <i class="fab fa-twitter"></i> </a> </li>
                            <li> <a href="#"> <i class="fab fa-linkedin-in"></i> </a> </li> --}}
                            <li> <a target="_blank" href="https://www.facebook.com/ExcelIdCardSolutions"> <i class="fab fa-facebook-f"></i> </a> </li>
                            <li> <a target="_blank" href="https://www.instagram.com/p/CLgPXD7nyXz/?igshid=spya82794cjk"> <i class="fab fa-instagram"></i> </a> </li>
                        </ul>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-12 footer-widget">
                        <h5 class="widget-title">Information</h5>
                        <ul>
                            <li> <a href="index.html">Home</a> </li>
                            <li> <a href="blog-grid.html">Blog</a> </li>
                            <li> <a href="about-us.html">About Us</a> </li>
                            <li> <a href="shop.html">Shop</a> </li>
                            <li> <a href="contact-us.html">Contact Us</a> </li>
                        </ul>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-12 footer-widget">
                        <h5 class="widget-title">Others</h5>
                        <ul>
                            <li> <a href="wishlist.html">Wishlist</a> </li>
                            <li> <a href="services.html">Services</a> </li>
                            <li> <a href="product-single.html">Printer</a> </li>
                            <li> <a href="shop.html">Products</a> </li>
                            <li> <a href="blog-grid.html">Blog</a> </li>
                        </ul>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-3 col-sm-12 d-none d-lg-block footer-widget">
                        <h5 class="widget-title">Top Categories</h5>
                        <ul>
                            <li> <a href="#">Printers</a> </li>
                            <li> <a href="#">Print Outs</a> </li>
                            <li> <a href="#">Papers</a> </li>
                            <li> <a href="#">Back to School</a> </li>
                            <li> <a href="#">Pens</a> </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <!-- Footer Bottom -->
        <div class="sigma_footer-bottom">
            <div class="container">
                <div class="sigma_footer-copyright">
                    <p> Copyright © 2020. All Rights Reserved. </p>
                </div>
            </div>
        </div>

    </footer>
    @endif
    <!-- Footer End -->

    <!-- Vendor Scripts -->
    <script src="{{ asset('js/plugins/jquery-3.4.1.min.js') }}"></script>
    <script src="{{ asset('js/plugins/popper.min.js') }}"></script>
    <script src="{{ asset('js/plugins/bootstrap.min.js') }}"></script>
    <script src="{{ asset('js/plugins/imagesloaded.min.js') }}"></script>
    <script src="{{ asset('js/plugins/jquery.magnific-popup.min.js') }}"></script>
    <script src="{{ asset('js/plugins/jquery.countdown.min.js') }}"></script>
    <script src="{{ asset('js/plugins/jquery.waypoints.min.js') }}"></script>
    <script src="{{ asset('js/plugins/jquery.counterup.min.js') }}"></script>
    <script src="{{ asset('js/plugins/jquery.zoom.min.js') }}"></script>
    <script src="{{ asset('js/plugins/jquery.inview.min.js') }}"></script>
    <script src="{{ asset('js/plugins/jquery.event.move.js') }}"></script>
    <script src="{{ asset('js/plugins/wow.min.js') }}"></script>
    <script src="{{ asset('js/plugins/isotope.pkgd.min.js') }}"></script>
    <script src="{{ asset('js/plugins/slick.min.js') }}"></script>
    <script src="{{ asset('js/plugins/ion.rangeSlider.min.js') }}"></script>

    <!-- Tilakam Scripts -->
    <script src="{{ asset('js/main.js') }}"></script>

resources/views/user/order.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Order') }}
        </h2>
    </x-slot>
    <!-- Subheader Start -->
    <div class="sigma_subheader primary-bg">

        <img src="{{  asset('img/textures/3.png') }}" class="texture-3" alt="texture" />

        <!-- Top Left Wave -->
        <div class="sigma_subheader-shape circles">
            <div class="circle circle-lg circle-1 primary-dark-bg"></div>
            <div class="circle circle-sm circle-2 bg-white"></div>
            <div class="circle circle-md circle-3 secondary-bg"></div>
        </div>

        <!-- Bottom Wave -->
        <div class="sigma_subheader-shape waves">
            <div class="wave"></div>
            <div class="wave"></div>
        </div>

        <div class="container">
            <div class="sigma_subheader-inner">
                <h1>My Orders</h1>
            </div>
        </div>
    </div>
    <!-- Subheader End -->
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div class="container">
                    @if (count($orders) > 0)
                    <div class="card p-2">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Order Id</th>
                                    <th>Category Name</th>
                                    <th>Product Name</th>
                                    <th class="text-center">Design Selected</th>
                                    <th class="text-center">Status</th>
                                    <th class="text-center">Payment Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($orders as $key => $order)
                                <tr>
                                    <th scope="row">{{ $key + 1 }}</th>
                                    <td>{{ $order['order_id'] }}</td>
                                    <td>{{ $order['category_name'] }}</td>
                                    <td>{{ $order['product_name'] }}</td>
                                   
                                    <td class="text-center">
                                        @if ($order['design_id'] != 0)
                                            Pre-Selected Design
                                        @elseif ($order['design_id'] == 0)
                                            Custom Design
                                        @endif
                                    </td>
                                    <td class="text-center text-light">
                                        @if ($order['status'] == 0) <span class="badge bg-danger">Pending</span>
                                        @elseif ($order['status'] == 1) <span class="badge bg-primary">In Progress</span>
                                        @elseif ($order['status'] == 2) <span class="badge bg-success">Completed</span>
                                        @endif
                                    </td> 
                                    <td class="text-center text-light">
                                    @isset($order['paymentStatus'])
                                       @if($order['paymentStatus'] == 'paid')
                                        <span class="badge bg-success">Paid</span>
                                       @else
                                       <a target=”_blank” href="{{ $order['paymentLink'] }}" class="btn bg-light">Pay Now</a> 
                                       @endif
                                       @endisset
                                    </td> 
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {{-- {{ $orders->links() }} --}}
                    </div>
                    @else
                    <div class="container-fluid text-center">
                        <img src="https://cdn.dribbble.com/users/1168645/screenshots/3152485/no-orders_2x.png?compress=1&resize=400x300" style="width:70%; margin: 0px auto"/>
                        <h3>No Orders</h3>
                        <a class="btn btn-outline-success" href="{{ route('index') }}">GO TO HOMEPAGE</a>
                        <br/>
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</x-app-layout>